services:
  mongodb:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - ADDITIONAL_USERS=${ADDITIONAL_USERS}
        - MONGO_PORT=${MONGO_PORT}
    container_name: medienausleihe-mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - ADDITIONAL_USERS=${ADDITIONAL_USERS}
      - MONGO_PORT=${MONGO_PORT}
    volumes:
      - ../init-scripts:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db

volumes:
  mongodb_data: